
format = """
[](#7BC3C3)\
$os\
$username\
[](bg:#E8C48A fg:#7BC3C3)\
$directory\
[](fg:#E8C48A bg:#D99B8B)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#D99B8B bg:#7DC39B)\
$git_branch\
$git_status\
[](fg:#7DC39B bg:#8BB3D9)\
$time\
[](fg:#8BB3D9)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#7BC3C3 fg:#142735"
style_root = "bg:#7BC3C3 fg:#142735"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#7BC3C3 fg:#142735"
disabled = true # Disabled by default

[directory]
style = "bg:#E8C48A fg:#142735"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#7DC39B fg:#142735"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#7DC39B fg:#142735"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#D99B8B fg:#142735"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#8BB3D9 fg:#142735"
format = '[  $time ]($style)'
